name: Build and Test

on: workflow_dispatch


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v6

      - name: Docker build
        run: docker build -t my-app .

      - name: Docker push
        run: |
          docker login -u prashant6749 -p 123456789
          docker tag my-app prashant6749/my-app:latest
          docker push prashant6749/my-app:latest

      